### ISSUE TITLE
confused about performance on 8xA53

### ISSUE THREAD

**Issue by wl3b10s** [BUG1989/ncnn-benchmark#1]
i made ncnn with default option and use your benchmark test of squeezenet on 8*A53 CPU in ubuntu 16.04.

i got about 960ms with about 700% CPU usage which means nearly full use of 8 core.

this result is much far behind your performance on A17*4 platform.

do you have any suggestion or advice on what's wrong for my test?

**Comment by BUG1989** [comment]
1. This repo lib does not support arm linux system platform,which ncnn-lib do you used?
2. If you use the arm platform,please make sure that using the ncnn-android lib work on android platform;
3. Please try to use single model and report it's timeconsuming result;
4. Cortex-A53 is slower than Cortex-A17 in the same freq;
5. Good luck!
