### ISSUE TITLE
compiling options

### ISSUE THREAD

**Issue by coldgemini** [BUG1989/ncnn-benchmark#2]
which compiler and compiling options did you use? I tried on rk3288 but somehow my time is about twice yours.

**Comment by BUG1989** [comment]
platform : 9tripod(RK3288)
OS          : Android 5.1.1
compiler : android-ndk-r14b
options  :     
```
cmake -DCMAKE_TOOLCHAIN_FILE=../android.toolchain.cmake \
          -DANDROID_ABI="armeabi-v7a with NEON" \
          -DANDROID_NATIVE_API_LEVEL=android-9 \
          -DANDROID_FORCE_ARM_BUILD=OFF \
          -DANDROID_STL_FORCE_FEATURES=OFF ..
```
optimize : 
```
echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
sync
echo 3 > /proc/sys/vm/drop_caches
./demo
```

**Comment by coldgemini** [comment]
did you try compile without android?

**Comment by BUG1989** [comment]
Yes,I compiled it to hi3519 and it work OK

**Comment by coldgemini** [comment]
and what's your options for that? I compiled on arm and it's twice your time.
